spring.application.name=MajorProject
server.port=8090

# ===============================
# = DataSource Configuration
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / Hibernate Configuration
# ===============================
# Show SQL in console
spring.jpa.show-sql=true

# Format SQL output
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL auto (create, create-drop, update, validate, none)
spring.jpa.hibernate.ddl-auto=update

# MySQL 8 dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# = Connection Pool (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

jwt.secret=my-super-secret-key-which-is-at-least-32-bytes!
#jwt.expiration=360000
jwt.expiration=20000000 

spring.config.import=optional:classpath:application-credentials.properties


spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=
#spring.mail.password=
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
